# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_covid')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_covid')
    _covid = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_covid', [dirname(__file__)])
        except ImportError:
            import _covid
            return _covid
        try:
            _mod = imp.load_module('_covid', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _covid = swig_import_helper()
    del swig_import_helper
else:
    import _covid
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class Model_30(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Model_30, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Model_30, name)
    __repr__ = _swig_repr
    __swig_setmethods__["_day"] = _covid.Model_30__day_set
    __swig_getmethods__["_day"] = _covid.Model_30__day_get
    if _newclass:
        _day = _swig_property(_covid.Model_30__day_get, _covid.Model_30__day_set)
    __swig_setmethods__["size"] = _covid.Model_30_size_set
    __swig_getmethods__["size"] = _covid.Model_30_size_get
    if _newclass:
        size = _swig_property(_covid.Model_30_size_get, _covid.Model_30_size_set)

    def __init__(self):
        this = _covid.new_Model_30()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _covid.delete_Model_30
    __del__ = lambda self: None
Model_30_swigregister = _covid.Model_30_swigregister
Model_30_swigregister(Model_30)


def Model_to_file(r0_num, max_dur, mult):
    return _covid.Model_to_file(r0_num, max_dur, mult)
Model_to_file = _covid.Model_to_file

def Model_30_set(r0_num, max_dur, mult):
    return _covid.Model_30_set(r0_num, max_dur, mult)
Model_30_set = _covid.Model_30_set

def Model_30_get_size(this_model):
    return _covid.Model_30_get_size(this_model)
Model_30_get_size = _covid.Model_30_get_size

def Model_30_get_cases(this_model, day):
    return _covid.Model_30_get_cases(this_model, day)
Model_30_get_cases = _covid.Model_30_get_cases
# This file is compatible with both classic and new-style classes.


